/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exec;

import Objetos.TrataImagenes;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migue
 */
public class ExecGUI extends javax.swing.JFrame {
    private TrataImagenes ti = new TrataImagenes();
    private HashMap<Integer, String> rutasEnMemoria = new HashMap<Integer, String>();;
    /**
     * Creates new form ExecGUI         src/Imagenes/gato.pgm
     */
    public ExecGUI() {
        initComponents();
        this.jLabelError.setVisible(false);
        this.jButtonCaja.setVisible(false);
        this.jButtonFlipH.setVisible(false);
        this.jButtonFlipV.setVisible(false);
        this.jButtonGirarD.setVisible(false);
        this.jButtonGirarI.setVisible(false);
        this.jButtonNegativo.setVisible(false);
        this.jButtonCerrar.setVisible(false);
        this.jButtonGuardar.setVisible(false);
        this.jButton1.setVisible(false);
        
        iniciaLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIntroduceRuta = new javax.swing.JLabel();
        jButtonEnviarRuta = new javax.swing.JButton();
        jLabelError = new javax.swing.JLabel();
        jTextFieldRuta = new javax.swing.JTextField();
        jButtonGirarD = new javax.swing.JButton();
        jButtonGirarI = new javax.swing.JButton();
        jButtonFlipV = new javax.swing.JButton();
        jButtonFlipH = new javax.swing.JButton();
        jButtonNegativo = new javax.swing.JButton();
        jButtonCaja = new javax.swing.JButton();
        jLabelImagenes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableImagenes = new javax.swing.JTable();
        jButtonCerrar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelIntroduceRuta.setText("Introduce ruta o ID de la imagen:");

        jButtonEnviarRuta.setText("Enviar");
        jButtonEnviarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarRutaActionPerformed(evt);
            }
        });

        jLabelError.setText("Error");

        jTextFieldRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRutaActionPerformed(evt);
            }
        });

        jButtonGirarD.setText("Girar imagen derecha");
        jButtonGirarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirarDActionPerformed(evt);
            }
        });

        jButtonGirarI.setText("Girar imagen izquierda");
        jButtonGirarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGirarIActionPerformed(evt);
            }
        });

        jButtonFlipV.setText("Flip vertical");
        jButtonFlipV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipVActionPerformed(evt);
            }
        });

        jButtonFlipH.setText("Flip horizontal");
        jButtonFlipH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlipHActionPerformed(evt);
            }
        });

        jButtonNegativo.setText("Filtro negativo");
        jButtonNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegativoActionPerformed(evt);
            }
        });

        jButtonCaja.setText("Filtro caja");
        jButtonCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCajaActionPerformed(evt);
            }
        });

        jLabelImagenes.setText("Imagenes en carpeta \"Imagenes\"");

        jTableImagenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Archivo"
            }
        ));
        jScrollPane1.setViewportView(jTableImagenes);
        if (jTableImagenes.getColumnModel().getColumnCount() > 0) {
            jTableImagenes.getColumnModel().getColumn(0).setResizable(false);
            jTableImagenes.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtonCerrar.setText("Cerrar Imagen");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonNegativo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFlipH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonFlipV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGirarI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jButtonGirarD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIntroduceRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldRuta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEnviarRuta))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagenes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIntroduceRuta)
                    .addComponent(jLabelError))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEnviarRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGirarD)
                    .addComponent(jButtonCerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGirarI)
                    .addComponent(jButtonGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFlipV)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFlipH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNegativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCaja)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarRutaActionPerformed
        // TODO add your handling code here:
        String ruta, id;
        ruta = this.jTextFieldRuta.getText();
        id = ruta;
        try{
            ti.cierraImagen();
        }catch(Exception e){
        }
        if (ruta.replaceAll("[0-9]", "").length() == 0 && ruta.length() > 0) {
            ruta = this.rutasEnMemoria.get(Integer.parseInt(id));
        }
        try{
            ti = new TrataImagenes(ruta);
//            this.jLabelIntroduceRuta.setVisible(false);
            this.jLabelError.setVisible(false);
            //
            this.jButtonCaja.setVisible(true);
            this.jButtonFlipH.setVisible(true);
            this.jButtonFlipV.setVisible(true);
            this.jButtonGirarD.setVisible(true);
            this.jButtonGirarI.setVisible(true);
            this.jButtonNegativo.setVisible(true);
            this.jButtonCerrar.setVisible(true);
            this.jButtonGuardar.setVisible(true);
            //
            ti.muestraImagen(300);
        }catch(Exception e){
            this.jLabelError.setVisible(true);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEnviarRutaActionPerformed

    private void jButtonGirarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirarDActionPerformed
        // TODO add your handling code here:
        ti.girarDerecha();
        actualizarImagen();
    }//GEN-LAST:event_jButtonGirarDActionPerformed

    private void jButtonGirarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGirarIActionPerformed
        // TODO add your handling code here:
        ti.girarIzquierda();
        actualizarImagen();
    }//GEN-LAST:event_jButtonGirarIActionPerformed

    private void jButtonFlipVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipVActionPerformed
        // TODO add your handling code here:
        ti.flipVertical();
        actualizarImagen();
    }//GEN-LAST:event_jButtonFlipVActionPerformed

    private void jButtonFlipHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlipHActionPerformed
        // TODO add your handling code here:
        ti.flipHorizontal();
        actualizarImagen();
    }//GEN-LAST:event_jButtonFlipHActionPerformed

    private void jButtonNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegativoActionPerformed
        // TODO add your handling code here:
        ti.negativo();
        actualizarImagen();
    }//GEN-LAST:event_jButtonNegativoActionPerformed

    private void jButtonCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCajaActionPerformed
        // TODO add your handling code here:
        ti.filtroCaja();
        actualizarImagen();
    }//GEN-LAST:event_jButtonCajaActionPerformed

    private void jTextFieldRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRutaActionPerformed
        // TODO add your handling code here:
        jButtonEnviarRutaActionPerformed(evt);
    }//GEN-LAST:event_jTextFieldRutaActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        try{
            ti.cierraImagen();
        }catch(Exception e){
        }
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        try {
            // TODO add your handling code here:
            ti.guardar();
        } catch (IOException ex) {
            Logger.getLogger(ExecGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            ti.aumentarResolucion();
        } catch (Exception ex) {
            Logger.getLogger(ExecGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void actualizarImagen(){
        try {
            ti.grabar();
            ti.cierraImagen();
            ti.muestraImagen(300);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExecGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExecGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCaja;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonEnviarRuta;
    private javax.swing.JButton jButtonFlipH;
    private javax.swing.JButton jButtonFlipV;
    private javax.swing.JButton jButtonGirarD;
    private javax.swing.JButton jButtonGirarI;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNegativo;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelImagenes;
    private javax.swing.JLabel jLabelIntroduceRuta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableImagenes;
    private javax.swing.JTextField jTextFieldRuta;
    // End of variables declaration//GEN-END:variables

    private void iniciaLista() {
        try {
            String rutaAct = "";
            Object[] filaAct = new Object[2];
            DefaultTableModel tabla = (DefaultTableModel) this.jTableImagenes.getModel();
            File[] imagenes = ti.getImagenesFiles();
            rutasEnMemoria.clear();
            for (int i = 0; i < imagenes.length; i++) {
                rutaAct = imagenes[i].getPath();
                rutasEnMemoria.put(i, rutaAct);
                rutaAct = rutaAct.replaceAll("src.Imagenes.", "");
                filaAct[0] = i;
                filaAct[1] = rutaAct;
                tabla.addRow(filaAct);
            }
        } catch (Exception ex) {
            Logger.getLogger(ExecGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
